name = "hydroanalyzer_fortran"
version = "0.1.0"
license = "MIT"
author = "khaors"
maintainer = "khaors@gmail.com"
copyright = "Copyright 2025, khaors"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[dependencies]
error-handling = { git = "https://github.com/SINTEF/fortran-error-handling.git", tag = "v0.2.0" }
toml-f = {git = "https://github.com/toml-f/toml-f"}
csv-fortran = { git="https://github.com/jacobwilliams/csv-fortran.git" }
